#!/usr/bin/env node
// gen_wire_doc.js — writes docs/WIRE.md from the golden vectors the host tests assert.
//
// WHY THIS IS GENERATED AND NOT WRITTEN. The doc set this replaces was ~8 000 lines of prose
// about the bus, and its citations had rotted to the point where source comments pointed at
// `docs/PROTOCOL-NOTES.md §17` (that file has ten sections) and `docs/DISPLAY-INIT-SPEC.md`
// (a different repository). Prose about bytes drifts from the bytes, silently, because
// nothing checks it.
//
// A golden vector cannot drift: `pio test -e native` fails the moment the builder stops
// emitting it. So the vectors ARE the specification, and this file only formats them.
//
//   node tools/gen_wire_doc.js          write docs/WIRE.md
//   node tools/gen_wire_doc.js --check   exit 1 if docs/WIRE.md is stale (for CI)
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'docs', 'WIRE.md');

// A frame literal: {0x151, 8, {0x05, 0x56, ...}, false}
const FRAME = /\{\s*(0x[0-9A-Fa-f]+)\s*,\s*(\d+)\s*,\s*\{([^}]*)\}\s*,\s*(true|false)\s*\}/g;

function frames(body) {
  const out = [];
  let m;
  FRAME.lastIndex = 0;
  while ((m = FRAME.exec(body))) {
    const bytes = m[3].split(',').map(s => s.trim()).filter(Boolean).map(tok => {
      // Character literals appear in vectors built from real strings: 'H', 'E', 'L'…
      const c = tok.match(/^'(.)'$/);
      if (c) return { hex: c[1].charCodeAt(0).toString(16).toUpperCase().padStart(2, '0'),
                      ch: c[1] };
      const v = parseInt(tok, 16);
      return { hex: Number.isNaN(v) ? tok : v.toString(16).toUpperCase().padStart(2, '0') };
    });
    const len = parseInt(m[2], 10);
    out.push({ id: parseInt(m[1], 16), len, bytes: bytes.slice(0, len) });
  }
  return out;
}

// Comments immediately above a declaration are the only prose that survives, because they
// sit next to the assertion and die with it.
function leadComment(src, at) {
  const before = src.slice(0, at).split('\n');
  const lines = [];
  for (let i = before.length - 2; i >= 0; --i) {
    const t = before[i].trim();
    if (!t.startsWith('//')) break;
    lines.unshift(t.replace(/^\/\/ ?/, ''));
  }
  return lines.join('\n').trim();
}

function parseSuite(file) {
  const src = fs.readFileSync(file, 'utf8');
  const vectors = [];
  // const Frame kName[] = { … };   and   const Frame kName = { … };
  const DECL = /const\s+Frame\s+(k[A-Za-z0-9_]+)\s*(\[\])?\s*=\s*([\s\S]*?);\n/g;
  let m;
  while ((m = DECL.exec(src))) {
    vectors.push({ name: m[1], frames: frames(m[3]), comment: leadComment(src, m.index) });
  }
  // void test_name(void) { … }
  const tests = [];
  const FN = /void\s+(test_[A-Za-z0-9_]+)\s*\(void\)\s*\{/g;
  while ((m = FN.exec(src))) {
    let depth = 1, i = FN.lastIndex;
    while (i < src.length && depth > 0) {
      if (src[i] === '{') ++depth;
      else if (src[i] === '}') --depth;
      ++i;
    }
    tests.push({ name: m[1], body: src.slice(FN.lastIndex, i) });
  }
  for (const v of vectors) {
    v.assertedBy = tests.filter(t => new RegExp(`\\b${v.name}\\b`).test(t.body)).map(t => t.name);
  }
  return { suite: path.basename(path.dirname(file)), vectors };
}

function render(suites) {
  const L = [];
  L.push('<!-- GENERATED by tools/gen_wire_doc.js — do not edit. Edit the test vectors. -->');
  L.push('# The wire, as the tests assert it');
  L.push('');
  L.push('Every frame below is a golden vector in `test/`, checked byte for byte by');
  L.push('`pio test -e native`. **If a builder stops emitting it, CI goes red** — which is the');
  L.push('only reason to believe a document about a bus.');
  L.push('');
  L.push('This file is generated. To change it, change the vector; to add a note, put the');
  L.push('comment above the vector, where it dies with the assertion it describes.');
  L.push('');
  L.push('> **What is NOT here is not attested.** ~8 000 lines of prose about this protocol');
  L.push('> were deleted on 2026-08-08: inference, third-party source reconstruction and');
  L.push('> transcription of captures we still have. Raw evidence lives in `captures/`;');
  L.push('> what has been seen on real glass lives in `docs/BENCH-VERIFIED.md`.');
  L.push('');

  let total = 0, orphans = 0;
  for (const s of suites) {
    if (!s.vectors.length) continue;
    L.push(`## \`${s.suite}\``);
    L.push('');
    for (const v of s.vectors) {
      total += v.frames.length;
      L.push(`### \`${v.name}\``);
      L.push('');
      if (v.comment) { L.push(v.comment.split('\n').map(x => '> ' + x).join('\n')); L.push(''); }
      L.push('```');
      for (const f of v.frames) {
        const hex = f.bytes.map(b => b.hex).join(' ');
        const ascii = f.bytes.some(b => b.ch)
          ? '    ' + f.bytes.map(b => b.ch || '.').join('')
          : '';
        L.push(`${f.id.toString(16).toUpperCase().padStart(3, '0')}  ${hex}${ascii}`);
      }
      L.push('```');
      L.push('');
      if (v.assertedBy.length) {
        L.push('asserted by ' + v.assertedBy.map(t => `\`${t}\``).join(', '));
      } else {
        ++orphans;
        L.push('**NOT ASSERTED BY ANY TEST — this vector proves nothing and should be deleted.**');
      }
      L.push('');
    }
  }
  L.push('---');
  L.push('');
  L.push(`${total} frames across ${suites.reduce((n, s) => n + s.vectors.length, 0)} vectors.` +
         (orphans ? `  **${orphans} unasserted.**` : ''));
  L.push('');
  return L.join('\n');
}

const files = [];
for (const d of fs.readdirSync(path.join(ROOT, 'test'))) {
  const f = path.join(ROOT, 'test', d, d + '.cpp');
  if (fs.existsSync(f)) files.push(f);
}
const out = render(files.map(parseSuite));

if (process.argv.includes('--check')) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (cur !== out) { console.error('docs/WIRE.md is stale — run: node tools/gen_wire_doc.js'); process.exit(1); }
  console.log('docs/WIRE.md is current');
} else {
  fs.writeFileSync(OUT, out);
  console.log(`wrote ${OUT}`);
}
